### ISSUE TITLE
建议用星号或加粗标记出最典型的常用配置项及最小可用配置项

### ISSUE THREAD

**Issue by InitialXKO** [yue1123/ts-config-helper#2]
大部分时间我们可能是想最快搞出一个能马上用的配置，然后再来慢慢调其他的选项

**Comment by yue1123** [comment]
可以，常用配置项这个确实需要标出来，不然很难找，我也想到了这个的，只是不知道哪些是常用配置项，没有参考源。至于最小可用配置项，后续会加一个预设的配置列表

**Comment by yue1123** [comment]
试试现在的版本
