### ISSUE TITLE
希望右侧 json key 的顺序可以和左侧描述标题的顺序一致

### ISSUE THREAD

**Issue by aimer-fan** [yue1123/ts-config-helper#3]
比如我在右侧的编辑器里输入以下配置：
```json
{
  "extends": "@vue/tsconfig/tsconfig.node.json",
  "compilerOptions": {
    "composite": true,
    "types": [
      "node"
    ]
  },
  "include": [
    "vite.config.*",
    "vitest.config.*",
    "cypress.config.*",
    "playwright.config.*"
  ]
}
``` 
我发现左侧标题的顺序是 `include`, `extends `, `compilerOptions.composite`, `compilerOptions.types` 这个有点违反直觉。

**Comment by aimer-fan** [comment]
或者是否可以通过双击 json 的 key，左侧的描述可以自动滚动到对应的描述，并高亮显示相关的描述。这样用户体验应该会更好。

**Comment by yue1123** [comment]
> 或者是否可以通过双击 json 的 key，左侧的描述可以自动滚动到对应的描述，并高亮显示相关的描述。这样用户体验应该会更好。

这个建议不错
